env:
  scenarios:
    - 2_1_m2o
  envs_per_scenario: 8
  history_length: 1
  reward: constrained
  default_port: 5555
  port_increment: 0
  multiprocess: False

training:
  max_timesteps: 1000000
  learning_rate: 0.00025
  gradient_clip: .5
  replay_size: 1000000

agent:
  save_name: ''
  evaluate: False
  agent_type: ADPG
  agent_features:
    - action
    - cnp_ratio
  linear_lr_decay: False
  activation_function: relu
  bias: false
  use_rnn: null
  adpg:
    action_multiplier_dec: 0.2
    action_multiplier_inc: 0.2
    rollout_length: 1024
    architecture:
      - 32
      - 16
    constraint: cnp

logging:
  wandb: False  # Logging using weights and biases
  wandb_run_name: unnamed  # Logging using weights and biases
  log_interval: 1024 # The minimum number of iterations before each log occurs
