env:
  scenarios:
    - "4_1_m2o_l"
    - "4_16_m2o_l"
    - "8_1_m2o_l"
    - "4_16_a2a_l"
    - "8_8_a2a_l"
    - "8_16_a2a_l"
    - "32_1_m2o_l"
  envs_per_scenario: 1
  history_length: 2
  reward: general
  port_increment: 10
  save_path: '../../reinforcement_learning/output/'  # relative path to nv_ccsim/sim/
  verbose: False
  restart_on_end: True
  multiprocess: False

training:
  max_num_updates: 1000
  learning_rate: 0.00025
  gradient_clip: .5

agent:
  save_name: ''
  evaluate: False
  agent_type: PPO
  agent_features:
    - action
#    - bandwidth
    - cnp_ratio
    - nack_ratio
#    - rtt_inflation
#    - cur_rate
  discount: .99
  linear_lr_decay: False
  ppo:
    action_multiplier_dec: 0.2
    action_multiplier_inc: 0.2
    discrete_actions: True
    action_weights:
      - 0.8
      - 0.95
      - 1
      - 1.05
      - 1.1
      - 1.2
    rollout_length: 64
    rollouts_per_batch: 4
    use_gae: False
    baseline_coeff: .5
    entropy_coeff: .01
    gae_tau: .95
    use_rnn: null
    activation_function: relu
    bias: False
    actor_architecture:
      - 32
      - 16
    critic_architecture:
      - 32
      - 16
    params:
      ppo_ratio_clip: .2
      ppo_batch_size: 4
      ppo_optimization_epochs: 4
  adpg:
    beta: 1.5
    target: 0.064
    scale: 12.5

logging:
  wandb: false  # Logging using weights and biases
  wandb_run_name: test  # Logging using weights and biases
  run_id: ''
  log_interval: 1024 # The minimum number of iterations before each log occurs
  limit_flows: False
  limit_hosts: 3
  limit_qps: 3
