env:
  scenarios:
    - "4_1_m2o_l"
    - "4_16_m2o_l"
    - "8_1_m2o_l"
    - "4_16_a2a_l"
    - "8_8_a2a_l"
    - "8_16_a2a_l"
    - "64_128_m2o_l"
  envs_per_scenario: 1
  history_length: 2
  omnet:
    simulator_path: ../nv_ccsim/sim  # relative to reinforcement_learning dir 
    exe_path: ../bin/ccsim_release  #../bin/ccsim_release  # relative to run_path
    config_path: omnetpp.ini
  reward: adpg_reward
  port_increment: 50
  save_path: '../../reinforcement_learning/output/'  # relative path to nv_ccsim/sim/
  verbose: False
  restart_on_end: True
  multiprocess: False


training:
  max_num_updates: 1000
  learning_rate: 0.01
  gradient_clip: 0.5

agent:
  save_name: ''
  checkpoint: ''
  evaluate: False
  agent_type: ADPG
  agent_features:
    - action
    - rtt_reward
  discount: .99
  linear_lr_decay: False
  activation_function: relu
  adpg:
    action_multiplier_dec: 0.2
    action_multiplier_inc: 0.2
    rollout_length: 3
    architecture:
      - 12
      - 12
    use_rnn: null
    target: 0.064
    action_loss_coeff: 1
    beta: 1.5
    loss_scale: 1.0
    scale: 12.5
    bias: False
    constraint: buffer
    loss_batch: 0 # use batch of agents in rollout instead of all agents
    max_batch_size: 8192
    max_step_size: 5000
    base_rtt: 8192.0
    warmup_length: 1024
    warmup_updates: 50

logging:
  wandb: false  # Logging using weights and biases
  wandb_run_name: test  # Logging using weights and biases
  run_id: ''
  min_log_interval: 1024 # The minimum number of iterations before each log occurs
  num_tests_to_log: 1
  limit_flows: False
  limit_hosts: 3
  limit_qps: 3
