program: sweep.py
method: grid
parameters:
  default_config:
    values: [telemetry_deterministic, rtt_deterministic, cnp_deterministic]
  additional_agent_feature_0:
    values: [switch_rate]
  additional_agent_feature_1:
    values: [bandwidth]
  additional_agent_feature_2:
    values: [requested_rate]
  architecture_index:
    values: [0, 1, 2, 3]
  use_lstm:
    values: [True, False]
